name: motocheck
description: MotoCheck – Bike Legality & Safety App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  model_viewer_plus: ^1.7.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  shared_preferences: ^2.5.5
  cloud_firestore: ^6.3.0
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.13.0
  permission_handler: ^11.3.1
  audioplayers: ^6.6.0
  torch_light: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

