// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMlJeiQkyw0Q7c9dN4OZGG9Wyswf6nNEg',
    appId: '1:196266510615:web:303b449f3abf7939440f52',
    messagingSenderId: '196266510615',
    projectId: 'motocheck-36930',
    authDomain: 'motocheck-36930.firebaseapp.com',
    storageBucket: 'motocheck-36930.firebasestorage.app',
    measurementId: 'G-BKFXC6TGDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZE17JG0MMIqjhOMZcplg9lsmfuINRniU',
    appId: '1:196266510615:android:4723d8b283978fb5440f52',
    messagingSenderId: '196266510615',
    projectId: 'motocheck-36930',
    storageBucket: 'motocheck-36930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9czLZRSkIiMrlUUFJZ34IBCYw_3aBjio',
    appId: '1:196266510615:ios:4954c389ea82a484440f52',
    messagingSenderId: '196266510615',
    projectId: 'motocheck-36930',
    storageBucket: 'motocheck-36930.firebasestorage.app',
    androidClientId: '196266510615-gcluhtjbt5mqunjf1ph2rl7drg3kruam.apps.googleusercontent.com',
    iosClientId: '196266510615-c7q2reugahc2euj9e67nddmua54p1url.apps.googleusercontent.com',
    iosBundleId: 'com.example.motocheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9czLZRSkIiMrlUUFJZ34IBCYw_3aBjio',
    appId: '1:196266510615:ios:4954c389ea82a484440f52',
    messagingSenderId: '196266510615',
    projectId: 'motocheck-36930',
    storageBucket: 'motocheck-36930.firebasestorage.app',
    androidClientId: '196266510615-gcluhtjbt5mqunjf1ph2rl7drg3kruam.apps.googleusercontent.com',
    iosClientId: '196266510615-c7q2reugahc2euj9e67nddmua54p1url.apps.googleusercontent.com',
    iosBundleId: 'com.example.motocheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMlJeiQkyw0Q7c9dN4OZGG9Wyswf6nNEg',
    appId: '1:196266510615:web:b0dd6cd84b22e016440f52',
    messagingSenderId: '196266510615',
    projectId: 'motocheck-36930',
    authDomain: 'motocheck-36930.firebaseapp.com',
    storageBucket: 'motocheck-36930.firebasestorage.app',
    measurementId: 'G-8P4XWG2DC5',
  );
}
